titel: 'Skitour und Eisklettern in Norwegen'
zusammenfassung: 'Nachdem wir uns auf einer Skitour durch das südliche Jotunheimen aufgewärmt hatten, ging es für vier Tag in "Eurpas Eiskletter Mekka".'
datum: '2006-04-28'