titel: 'Skitour und Eisklettern im Engadin'
zusammenfassung: 'Wie schon im letzten Jahr, ging es zwischen Weihnachten und Neujahr in die Schweiz, diesmal ins Unterengadin. Obwohl wir nur eine Woche und wenig Schnee hatten, sind ein paar tolle Touren zustande gekommen …'
autor: 'Richard'
datum: '2006-12-31'