titel: 'Skitour Sustenhorn'
zusammenfassung: 'Kurz, aber oho: Vom Steigletscher am Sustenpass starten wir zur Ski-Besteigung des Sustenhorns (3503 m) und des Gwächtenhorns (3420 m). Nachmittags in der Nähe von Meiringen chillen und klettern wir noch ein wenig in der Sonne.'
datum: '2012-05-13'
autor: 'Friedjoff'
teaser: 'fotos/06.jpg'