titel: 'Skitour Haute Route'
zusammenfassung: 'Auf der Königin der Skitouren von Chamonix nach Zermatt mit Überschreitung des Pigne d´Arolla (3790m). Von den Ausläufern des Mont Blanc führt die Haute Route über die höchsten Pässe und Gletscher durch die Waliser Alpen bis nach Zermatt am Fuße des Matterhorns. Im Februar 2008 ziehen wir hier acht Tage lang unsere Spur durchs Hochgebirge.'
autor: 'Richard'
datum: '2008-04-28'