titel: 'Eisklettern in Rjukan'
zusammenfassung: 'Nach unserer Skitour im Jotunheimen verbrachten wir vier Tage in "Europas Eiskletter Mekka", der südnorwegischen Stadt Rjukan. Mit geliehener Ausrüstung machten wir hier unsere ersten Erfahrung am Eis.'
autor: 'Mathis'
datum: '2006-04-28'