titel: 'Skitour Jotunheimen'
zusammenfassung: 'Neun Tage lang durchwanderten wir in den Wintersemesterferien 2006 mit Tourenskiern das höchste Gebirge Skandinaviens. Von kalten Nächten und traumhaften Abfahrten...'
autor: 'Mathis'
datum: '2006-04-29'