titel: 'Skitour Urner Alpen'
zusammenfassung: 'Die anspruchsvolle Durchquerung der abgelegenen Urner Alpen im Hochwinter – Eindrücke von einer abwechslungsreichen Skitour in einsamem Gelände.'
datum: '2012-02-27'
autor: 'Richard'