titel: 'Skitour im Berner Oberland'
zusammenfassung: 'Nach drei Tagestouren auf umliegende Berge ging es in vier Tage mit Zelt und Rucksack vom Rosenlaui über die Wart zum Faulhorn und zurück.'
datum: '2006-02-02'