titel: 'Trekking in Marokko'
zusammenfassung: 'Richie hat uns in Richtung Heimat verlassen, während Hörbe und ich (Mathis) knapp zwei weitere Wochen in Marokko verbringen. Dabei lernen wir die Vielseitigkeit des Landes erst so richtig kennen. Von Kletterrouten, Dünen in der Sandwüste und Surfbrettern …'
autor: 'Mathis'
datum: '2006-08-28'