titel: 'Bike tour Danube'
zusammenfassung: 'two young people had the urge to explore the eastern European countries before they where all run over by the west. the plan was to ride with bikes along the Danube river, from the spring in Donaueschingen all the way to the delta. during the seven weeks and 3300 kilometres we passed 9 countries and several capitals.'
autor: 'Hannah'
datum: '2008-06-23'